#cloud-config
coreos:
  etcd2:
    discovery: ${etcd_discovery_url}
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380

    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://$private_ipv4:2380

  #   cert-file: /etc/ssl/etcd/server.pem
  #   key-file: /etc/ssl/etcd/server-key.pem
  #   client-cert-auth: true
  #   trusted-ca-file: /etc/ssl/etcd/ca.pem
  #   peer-cert-file: /etc/ssl/etcd/server.pem
  #   peer-key-file: /etc/ssl/etcd/server-key.pem
  #   peer-client-cert-auth: true
  #   peer-trusted-ca-file: /etc/ssl/etcd/ca.pem
  # flannel:
  #   etcd_endpoints: https://$private_ipv4:2379
  #   etcd_cafile: /etc/ssl/etcd/ca.pem
  #   etcd_certfile: /etc/ssl/etcd/server.pem
  #   etcd_keyfile: /etc/ssl/etcd/server-key.pem
  # locksmith:
  #   endpoint: https://$private_ipv4:2379
  #   etcd_cafile: /etc/ssl/etcd/ca.pem
  #   etcd_certfile: /etc/ssl/etcd/server.pem
  #   etcd_keyfile: /etc/ssl/etcd/server-key.pem
  update:
    reboot-strategy: "etcd-lock"
  units:
    - name: "etcd2.service"
      command: "start"
    - name: "docker-tcp.socket"
        command: "start"
        enable: "true"
        content: |
          [Unit]
          Description=TCP socket for the Docker API

          [Socket]
          ListenStream=2375
          Service=docker.service
          BindIPv6Only=both

          [Install]
          WantedBy=sockets.target
